"""48 Bücher als dict
 Goodreads
🔗 https://www.goodreads.com/
rating, rezenzionen, sprache,alter, verfilmung

Wikipedia (List of best-selling books)
🔗 https://en.wikipedia.org/wiki/List_of_best-selling_books

copy,übersetzung,verfilmung,autor,Land, Jahr
WorldCat
🔗 https://www.worldcat.org/

übersetzung,Ausgabe,sprache, meta
Open Library
🔗 https://openlibrary.org/
meta über autor,genre..

"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

books_50_real = [
    {
        "Title": "Don Quixote",
        "Author": "Miguel de Cervantes",
        "Genre": "Fiction",
        "Original_Language": "Spanish",
        "Year_Published": 1605,
        "Estimated_Readers_Millions": 500,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 500,
        "Adaptations_Film_TV": 10,
        "Translated_Languages": 50,
        "Goodreads_Rating": 3.9,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 15,
        "Country_of_Author": "Spain",
    },
    {
        "Title": "Harry Potter and the Philosopher's Stone",
        "Author": "J.K. Rowling",
        "Genre": "Fantasy",
        "Original_Language": "English",
        "Year_Published": 1997,
        "Estimated_Readers_Millions": 120,
        "Target_Age": "Children/Teen",
        "Copies_Sold_Millions": 120,
        "Adaptations_Film_TV": 8,
        "Translated_Languages": 80,
        "Goodreads_Rating": 4.5,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 30,
        "Country_of_Author": "United Kingdom",
    },
    {
        "Title": "The Lord of the Rings",
        "Author": "J.R.R. Tolkien",
        "Genre": "Fantasy",
        "Original_Language": "English",
        "Year_Published": 1954,
        "Estimated_Readers_Millions": 150,
        "Target_Age": "Teen/Adult",
        "Copies_Sold_Millions": 150,
        "Adaptations_Film_TV": 9,
        "Translated_Languages": 70,
        "Goodreads_Rating": 4.5,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 20,
        "Country_of_Author": "United Kingdom",
    },
    {
        "Title": "Pride and Prejudice",
        "Author": "Jane Austen",
        "Genre": "Romance",
        "Original_Language": "English",
        "Year_Published": 1813,
        "Estimated_Readers_Millions": 120,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 120,
        "Adaptations_Film_TV": 6,
        "Translated_Languages": 35,
        "Goodreads_Rating": 4.3,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 12,
        "Country_of_Author": "United Kingdom",
    },
    {
        "Title": "To Kill a Mockingbird",
        "Author": "Harper Lee",
        "Genre": "Fiction",
        "Original_Language": "English",
        "Year_Published": 1960,
        "Estimated_Readers_Millions": 40,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 40,
        "Adaptations_Film_TV": 2,
        "Translated_Languages": 40,
        "Goodreads_Rating": 4.3,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 8,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Great Gatsby",
        "Author": "F. Scott Fitzgerald",
        "Genre": "Fiction",
        "Original_Language": "English",
        "Year_Published": 1925,
        "Estimated_Readers_Millions": 30,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 30,
        "Adaptations_Film_TV": 5,
        "Translated_Languages": 25,
        "Goodreads_Rating": 3.9,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 5,
        "Country_of_Author": "USA",
    },
    {
        "Title": "One Hundred Years of Solitude",
        "Author": "Gabriel García Márquez",
        "Genre": "Magical Realism",
        "Original_Language": "Spanish",
        "Year_Published": 1967,
        "Estimated_Readers_Millions": 50,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 50,
        "Adaptations_Film_TV": 2,
        "Translated_Languages": 45,
        "Goodreads_Rating": 4.1,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 7,
        "Country_of_Author": "Colombia",
    },
    {
        "Title": "The Catcher in the Rye",
        "Author": "J.D. Salinger",
        "Genre": "Fiction",
        "Original_Language": "English",
        "Year_Published": 1951,
        "Estimated_Readers_Millions": 65,
        "Target_Age": "Teen/Adult",
        "Copies_Sold_Millions": 65,
        "Adaptations_Film_TV": 3,
        "Translated_Languages": 30,
        "Goodreads_Rating": 3.8,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 10,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Hobbit",
        "Author": "J.R.R. Tolkien",
        "Genre": "Fantasy",
        "Original_Language": "English",
        "Year_Published": 1937,
        "Estimated_Readers_Millions": 100,
        "Target_Age": "Teen",
        "Copies_Sold_Millions": 100,
        "Adaptations_Film_TV": 3,
        "Translated_Languages": 60,
        "Goodreads_Rating": 4.3,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 15,
        "Country_of_Author": "United Kingdom",
    },
    {
        "Title": "War and Peace",
        "Author": "Leo Tolstoy",
        "Genre": "Historical Fiction",
        "Original_Language": "Russian",
        "Year_Published": 1869,
        "Estimated_Readers_Millions": 36,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 36,
        "Adaptations_Film_TV": 4,
        "Translated_Languages": 50,
        "Goodreads_Rating": 4.1,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 8,
        "Country_of_Author": "Russia",
    },
    {
        "Title": "The Alchemist",
        "Author": "Paulo Coelho",
        "Genre": "Adventure",
        "Original_Language": "Portuguese",
        "Year_Published": 1988,
        "Estimated_Readers_Millions": 65,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 65,
        "Adaptations_Film_TV": 0,
        "Translated_Languages": 80,
        "Goodreads_Rating": 3.9,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 12,
        "Country_of_Author": "Brazil",
    },
    {
        "Title": "The Chronicles of Narnia",
        "Author": "C.S. Lewis",
        "Genre": "Fantasy",
        "Original_Language": "English",
        "Year_Published": 1956,
        "Estimated_Readers_Millions": 85,
        "Target_Age": "Children/Teen",
        "Copies_Sold_Millions": 85,
        "Adaptations_Film_TV": 5,
        "Translated_Languages": 47,
        "Goodreads_Rating": 4.2,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 10,
        "Country_of_Author": "United Kingdom",
    },
    {
        "Title": "The Da Vinci Code",
        "Author": "Dan Brown",
        "Genre": "Thriller",
        "Original_Language": "English",
        "Year_Published": 2003,
        "Estimated_Readers_Millions": 80,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 80,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 44,
        "Goodreads_Rating": 3.8,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 25,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Kite Runner",
        "Author": "Khaled Hosseini",
        "Genre": "Fiction",
        "Original_Language": "English",
        "Year_Published": 2003,
        "Estimated_Readers_Millions": 35,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 35,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 40,
        "Goodreads_Rating": 4.3,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 6,
        "Country_of_Author": "USA",
    },
    {
        "Title": "Crime and Punishment",
        "Author": "Fyodor Dostoevsky",
        "Genre": "Classic",
        "Original_Language": "Russian",
        "Year_Published": 1866,
        "Estimated_Readers_Millions": 40,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 40,
        "Adaptations_Film_TV": 6,
        "Translated_Languages": 35,
        "Goodreads_Rating": 4.2,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 10,
        "Country_of_Author": "Russia",
    },
    {
        "Title": "The Hunger Games",
        "Author": "Suzanne Collins",
        "Genre": "Dystopian",
        "Original_Language": "English",
        "Year_Published": 2008,
        "Estimated_Readers_Millions": 65,
        "Target_Age": "Teen/Adult",
        "Copies_Sold_Millions": 65,
        "Adaptations_Film_TV": 4,
        "Translated_Languages": 50,
        "Goodreads_Rating": 4.3,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 18,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Girl with the Dragon Tattoo",
        "Author": "Stieg Larsson",
        "Genre": "Mystery",
        "Original_Language": "Swedish",
        "Year_Published": 2005,
        "Estimated_Readers_Millions": 30,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 30,
        "Adaptations_Film_TV": 2,
        "Translated_Languages": 45,
        "Goodreads_Rating": 4.1,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 8,
        "Country_of_Author": "Sweden",
    },
    {
        "Title": "The Fault in Our Stars",
        "Author": "John Green",
        "Genre": "Young Adult",
        "Original_Language": "English",
        "Year_Published": 2012,
        "Estimated_Readers_Millions": 40,
        "Target_Age": "Teen",
        "Copies_Sold_Millions": 40,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 30,
        "Goodreads_Rating": 4.2,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 12,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Road",
        "Author": "Cormac McCarthy",
        "Genre": "Post-Apocalyptic",
        "Original_Language": "English",
        "Year_Published": 2006,
        "Estimated_Readers_Millions": 20,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 20,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 28,
        "Goodreads_Rating": 4.0,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 5,
        "Country_of_Author": "USA",
    },
    {
        "Title": "Gone with the Wind",
        "Author": "Margaret Mitchell",
        "Genre": "Historical Fiction",
        "Original_Language": "English",
        "Year_Published": 1936,
        "Estimated_Readers_Millions": 30,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 30,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 35,
        "Goodreads_Rating": 4.3,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 8,
        "Country_of_Author": "USA",
    },
    {
        "Title": "Jane Eyre",
        "Author": "Charlotte Brontë",
        "Genre": "Gothic Fiction",
        "Original_Language": "English",
        "Year_Published": 1847,
        "Estimated_Readers_Millions": 20,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 20,
        "Adaptations_Film_TV": 5,
        "Translated_Languages": 30,
        "Goodreads_Rating": 4.1,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 6,
        "Country_of_Author": "United Kingdom",
    },
    {
        "Title": "1984",
        "Author": "George Orwell",
        "Genre": "Dystopian",
        "Original_Language": "English",
        "Year_Published": 1949,
        "Estimated_Readers_Millions": 60,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 60,
        "Adaptations_Film_TV": 4,
        "Translated_Languages": 65,
        "Goodreads_Rating": 4.2,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 10,
        "Country_of_Author": "United Kingdom",
    },
    {
        "Title": "The Little Prince",
        "Author": "Antoine de Saint-Exupéry",
        "Genre": "Fable",
        "Original_Language": "French",
        "Year_Published": 1943,
        "Estimated_Readers_Millions": 140,
        "Target_Age": "Children/All",
        "Copies_Sold_Millions": 140,
        "Adaptations_Film_TV": 6,
        "Translated_Languages": 250,
        "Goodreads_Rating": 4.3,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 20,
        "Country_of_Author": "France",
    },
    {
        "Title": "The Book Thief",
        "Author": "Markus Zusak",
        "Genre": "Historical Fiction",
        "Original_Language": "English",
        "Year_Published": 2005,
        "Estimated_Readers_Millions": 20,
        "Target_Age": "Teen/Adult",
        "Copies_Sold_Millions": 20,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 40,
        "Goodreads_Rating": 4.4,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 5,
        "Country_of_Author": "Australia",
    },
    {
        "Title": "The Shining",
        "Author": "Stephen King",
        "Genre": "Horror",
        "Original_Language": "English",
        "Year_Published": 1977,
        "Estimated_Readers_Millions": 30,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 30,
        "Adaptations_Film_TV": 2,
        "Translated_Languages": 35,
        "Goodreads_Rating": 4.2,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 7,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Picture of Dorian Gray",
        "Author": "Oscar Wilde",
        "Genre": "Gothic Fiction",
        "Original_Language": "English",
        "Year_Published": 1890,
        "Estimated_Readers_Millions": 25,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 25,
        "Adaptations_Film_TV": 4,
        "Translated_Languages": 30,
        "Goodreads_Rating": 4.1,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 6,
        "Country_of_Author": "Ireland",
    },
    {
        "Title": "The Brothers Karamazov",
        "Author": "Fyodor Dostoevsky",
        "Genre": "Philosophical Fiction",
        "Original_Language": "Russian",
        "Year_Published": 1880,
        "Estimated_Readers_Millions": 20,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 20,
        "Adaptations_Film_TV": 3,
        "Translated_Languages": 40,
        "Goodreads_Rating": 4.3,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 6,
        "Country_of_Author": "Russia",
    },
    {
        "Title": "Dracula",
        "Author": "Bram Stoker",
        "Genre": "Horror",
        "Original_Language": "English",
        "Year_Published": 1897,
        "Estimated_Readers_Millions": 25,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 25,
        "Adaptations_Film_TV": 8,
        "Translated_Languages": 44,
        "Goodreads_Rating": 3.9,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 7,
        "Country_of_Author": "Ireland",
    },
    {
        "Title": "Les Misérables",
        "Author": "Victor Hugo",
        "Genre": "Historical Fiction",
        "Original_Language": "French",
        "Year_Published": 1862,
        "Estimated_Readers_Millions": 35,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 35,
        "Adaptations_Film_TV": 6,
        "Translated_Languages": 45,
        "Goodreads_Rating": 4.2,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 9,
        "Country_of_Author": "France",
    },
    {
        "Title": "Moby-Dick",
        "Author": "Herman Melville",
        "Genre": "Adventure",
        "Original_Language": "English",
        "Year_Published": 1851,
        "Estimated_Readers_Millions": 20,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 20,
        "Adaptations_Film_TV": 4,
        "Translated_Languages": 40,
        "Goodreads_Rating": 3.6,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 5,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Divine Comedy",
        "Author": "Dante Alighieri",
        "Genre": "Epic Poetry",
        "Original_Language": "Italian",
        "Year_Published": 1320,
        "Estimated_Readers_Millions": 40,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 40,
        "Adaptations_Film_TV": 2,
        "Translated_Languages": 60,
        "Goodreads_Rating": 4.0,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 10,
        "Country_of_Author": "Italy",
    },
    {
        "Title": "Don Quixote",
        "Author": "Miguel de Cervantes",
        "Genre": "Classic",
        "Original_Language": "Spanish",
        "Year_Published": 1605,
        "Estimated_Readers_Millions": 70,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 70,
        "Adaptations_Film_TV": 5,
        "Translated_Languages": 140,
        "Goodreads_Rating": 3.9,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 12,
        "Country_of_Author": "Spain",
    },
    {
        "Title": "The Girl with the Dragon Tattoo",
        "Author": "Stieg Larsson",
        "Genre": "Crime Thriller",
        "Original_Language": "Swedish",
        "Year_Published": 2005,
        "Estimated_Readers_Millions": 40,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 40,
        "Adaptations_Film_TV": 2,
        "Translated_Languages": 50,
        "Goodreads_Rating": 4.1,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 10,
        "Country_of_Author": "Sweden",
    },
    {
        "Title": "The Road",
        "Author": "Cormac McCarthy",
        "Genre": "Post-Apocalyptic",
        "Original_Language": "English",
        "Year_Published": 2006,
        "Estimated_Readers_Millions": 10,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 10,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 25,
        "Goodreads_Rating": 4.0,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 3,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Shadow of the Wind",
        "Author": "Carlos Ruiz Zafón",
        "Genre": "Mystery",
        "Original_Language": "Spanish",
        "Year_Published": 2001,
        "Estimated_Readers_Millions": 15,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 15,
        "Adaptations_Film_TV": 0,
        "Translated_Languages": 40,
        "Goodreads_Rating": 4.3,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 4,
        "Country_of_Author": "Spain",
    },
    {
        "Title": "The Name of the Rose",
        "Author": "Umberto Eco",
        "Genre": "Historical Mystery",
        "Original_Language": "Italian",
        "Year_Published": 1980,
        "Estimated_Readers_Millions": 50,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 50,
        "Adaptations_Film_TV": 2,
        "Translated_Languages": 45,
        "Goodreads_Rating": 4.1,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 6,
        "Country_of_Author": "Italy",
    },
    {
        "Title": "The Bell Jar",
        "Author": "Sylvia Plath",
        "Genre": "Semi-Autobiographical Fiction",
        "Original_Language": "English",
        "Year_Published": 1963,
        "Estimated_Readers_Millions": 10,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 10,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 20,
        "Goodreads_Rating": 4.0,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 2,
        "Country_of_Author": "USA",
    },
    {
        "Title": "Outlander",
        "Author": "Diana Gabaldon",
        "Genre": "Historical Fantasy",
        "Original_Language": "English",
        "Year_Published": 1991,
        "Estimated_Readers_Millions": 30,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 30,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 27,
        "Goodreads_Rating": 4.2,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 5,
        "Country_of_Author": "USA",
    },
    {
        "Title": "Life of Pi",
        "Author": "Yann Martel",
        "Genre": "Philosophical Fiction",
        "Original_Language": "English",
        "Year_Published": 2001,
        "Estimated_Readers_Millions": 15,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 15,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 40,
        "Goodreads_Rating": 3.9,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 3,
        "Country_of_Author": "Canada",
    },
    {
        "Title": "Never Let Me Go",
        "Author": "Kazuo Ishiguro",
        "Genre": "Science Fiction",
        "Original_Language": "English",
        "Year_Published": 2005,
        "Estimated_Readers_Millions": 8,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 8,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 30,
        "Goodreads_Rating": 4.0,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 2,
        "Country_of_Author": "United Kingdom",
    },
    {
        "Title": "Love in the Time of Cholera",
        "Author": "Gabriel García Márquez",
        "Genre": "Romance",
        "Original_Language": "Spanish",
        "Year_Published": 1985,
        "Estimated_Readers_Millions": 30,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 30,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 46,
        "Goodreads_Rating": 4.1,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 5,
        "Country_of_Author": "Colombia",
    },
    {
        "Title": "The Fault in Our Stars",
        "Author": "John Green",
        "Genre": "Young Adult Romance",
        "Original_Language": "English",
        "Year_Published": 2012,
        "Estimated_Readers_Millions": 23,
        "Target_Age": "Teen/Young Adult",
        "Copies_Sold_Millions": 23,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 50,
        "Goodreads_Rating": 4.1,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 6,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Maze Runner",
        "Author": "James Dashner",
        "Genre": "Dystopian",
        "Original_Language": "English",
        "Year_Published": 2009,
        "Estimated_Readers_Millions": 25,
        "Target_Age": "Teen",
        "Copies_Sold_Millions": 25,
        "Adaptations_Film_TV": 3,
        "Translated_Languages": 30,
        "Goodreads_Rating": 4.0,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 5,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Lovely Bones",
        "Author": "Alice Sebold",
        "Genre": "Drama",
        "Original_Language": "English",
        "Year_Published": 2002,
        "Estimated_Readers_Millions": 20,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 20,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 39,
        "Goodreads_Rating": 3.8,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 4,
        "Country_of_Author": "USA",
    },
    {
        "Title": "Room",
        "Author": "Emma Donoghue",
        "Genre": "Drama",
        "Original_Language": "English",
        "Year_Published": 2010,
        "Estimated_Readers_Millions": 10,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 10,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 30,
        "Goodreads_Rating": 4.1,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 3,
        "Country_of_Author": "Ireland",
    },
    {
        "Title": "The Secret",
        "Author": "Rhonda Byrne",
        "Genre": "Self-help",
        "Original_Language": "English",
        "Year_Published": 2006,
        "Estimated_Readers_Millions": 30,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 30,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 50,
        "Goodreads_Rating": 3.7,
        "Has_Major_Awards": "No",
        "Pirated_Estimate_Millions": 10,
        "Country_of_Author": "Australia",
    },
    {
        "Title": "Thinking, Fast and Slow",
        "Author": "Daniel Kahneman",
        "Genre": "Non-fiction",
        "Original_Language": "English",
        "Year_Published": 2011,
        "Estimated_Readers_Millions": 15,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 15,
        "Adaptations_Film_TV": 0,
        "Translated_Languages": 40,
        "Goodreads_Rating": 4.2,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 5,
        "Country_of_Author": "USA",
    },
    {
        "Title": "The Martian",
        "Author": "Andy Weir",
        "Genre": "Science Fiction",
        "Original_Language": "English",
        "Year_Published": 2011,
        "Estimated_Readers_Millions": 20,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 20,
        "Adaptations_Film_TV": 1,
        "Translated_Languages": 35,
        "Goodreads_Rating": 4.4,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 5,
        "Country_of_Author": "USA",
    },
    {
        "Title": "A Man Called Ove",
        "Author": "Fredrik Backman",
        "Genre": "Contemporary",
        "Original_Language": "Swedish",
        "Year_Published": 2012,
        "Estimated_Readers_Millions": 15,
        "Target_Age": "Adult",
        "Copies_Sold_Millions": 15,
        "Adaptations_Film_TV": 2,
        "Translated_Languages": 40,
        "Goodreads_Rating": 4.3,
        "Has_Major_Awards": "Yes",
        "Pirated_Estimate_Millions": 4,
        "Country_of_Author": "Sweden",
    },
]


df = pd.DataFrame(books_50_real)

# Titel
st.title("📚 Interaktives Buch-Dashboard")
# Genre-Auswahl
genre = st.selectbox(
    "Wähle ein Genre:", df["Genre"].unique()
)  # Genre-Auswahl mit Dropdown-Menü (alle vorhandenen Genres)
filtered = df[df["Genre"] == genre]  # Daten nach gewähltem Genre filtern

# Tabelle anzeigen
st.write(filtered)

# Visualisierung
st.subheader("Verkäufe im Genre")  # Zwischenüberschrift
fig, ax = plt.subplots()  # Neues Diagramm erstellen
ax.bar(
    filtered["Title"], filtered["Copies_Sold_Millions"]
)  # X-Achse: Buchtitel, Y-Achse: Verkaufszahlen in mln
plt.xticks(rotation=90)  # X-Achsenbeschriftung drehen
st.pyplot(fig)  # Diagramm in Streamlit anzeigen
